In [ ]:
import numpy as np 

In [3]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25],
                [26,27,28,29,30]])
arr[0]

array([1, 2, 3, 4, 5])

In [4]:
arr[5]  #last row

array([26, 27, 28, 29, 30])

In [5]:
arr[:, 2]   #third column

array([ 3,  8, 13, 18, 23, 28])

In [6]:
arr[:3]  #first three rows

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
arr[-3:]  #last three rows

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[:, :2]  #first two colum

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [9]:
arr[:, -2:]   #last two columns

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [10]:
arr[1:4, 2:5]   #rows 1-3, columns 2-4

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [11]:
arr[2:]   #index 2 se aage ki sabhi rows

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[:, 3:]  #index 3 se aage ke sabhi columns

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [13]:
arr[::2] #every second row 

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [14]:
arr[:, ::2]  #every second column

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25],
       [26, 28, 30]])

In [15]:
arr[-3:, -2:] #botton right 3*2 block

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
arr[:4, :3]  # top left 4*3 block

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [17]:
arr[::-1]  #reverse row

array([[26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [18]:
arr[:, ::-1]   #reverse columns

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21],
       [30, 29, 28, 27, 26]])

In [19]:
arr[::-1, ::-1]  #reverse row and columns

array([[30, 29, 28, 27, 26],
       [25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [20]:
arr[2:4, 1:4] #middle 2*3 block

array([[12, 13, 14],
       [17, 18, 19]])

In [21]:
arr[[0,1]]  #first and last row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
arr[:, [0,-1]]  #first and last columns

array([[ 1,  5],
       [ 6, 10],
       [11, 15],
       [16, 20],
       [21, 25],
       [26, 30]])

In [23]:
arr[1::2] #all odd indexed rows

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])

In [24]:
arr[:, ::2]  #all even indexed columns

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25],
       [26, 28, 30]])

In [25]:
arr[4, 2]  #element at row index 4 

np.int64(23)

In [26]:
arr[:, 3]  #entire column containing the value 14

array([ 4,  9, 14, 19, 24, 29])

In [27]:
arr[[0,0,-1,-1,],[0,-1,0,-1]]  #the four corner elements

array([ 1,  5, 26, 30])

In [28]:
arr[:, 2]   #the central columns only

array([ 3,  8, 13, 18, 23, 28])

In [29]:
arr[1:5, ::2]  # rows 1to4 and every second columns

array([[ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [30]:
arr[::, 1:4]   #every row but only columns with indice 1,2 and 3

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [31]:
arr[2:4, 2:4]  #2*2 block from the center of the array

array([[13, 14],
       [18, 19]])